<div class="container-fluid h-100 ">
	<div class="row">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">   		
				<img src="/img/logo_grande.png" />
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form method="post" action="/autenticar">
		<h1 class="title">Acontecendo agora</h1>
		<h2 class="mt-5 subtitle">Inscreva-se hoje!</h2>

			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-secondary mb-2">Entrar</button>
				</div>
			</div>

			<?php if($this->view->login == 'erro') { ?>
				<div class="row">
					<div class="col">
						<span class="text text-danger">*E-mail e ou senha inválido(s)</span>
					</div>
				</div>
			<?php } ?>
		</form>

		<div class="row pl-5 pr-5">
			<div class="col pl-10 pr-5">
				<h3 class="ou">ou</h3>
			</div>
		</div>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<a href="/inscreverse" class="btn btn-secondary btn-block mb-2">Criar conta</a>
				<small class="form-text">
					Ao se inscrever, você concorda com os Termos de Serviço e a Política de Privacidade, incluindo o Uso de Cookies.
				</small>
			</div>	
		</div>


    </div>

  </div>
</div>